language: julia
os:
    # Temporarily commenting out osx because of Homebrew installation issue
    # of gcc 8.x. This causes the HDF5 build to attempt to build it from scratch
    # by downloading all of xcode which Travis CI then kills because it takes too long.
    # Refer to Matt Bauman's comment on JuliaIO/HDF5.jl issue 483, and
    # Andreas Noack's issue 27751 on Homebrew/homebrew-core.
    # - osx
    - linux
julia:
    - 0.6
notifications:
    email: false
addons:
  apt:
    packages:
    - hdf5-tools
    - libnlopt0
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --color=yes -e 'Pkg.clone(pwd()); Pkg.build("StateSpaceRoutines"); Pkg.test("StateSpaceRoutines"; coverage=true)'
branches:
  only:
    - master
after_success:
- julia -e 'cd(Pkg.dir("StateSpaceRoutines")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
# - julia -e 'Pkg.add("Documenter")'
# - julia -e 'cd(Pkg.dir("StateSpaceRoutines")); include(joinpath("docs", "make.jl"))'
